package com.ublwarriors.guacamole.model;

import java.util.ArrayList;
import java.util.List;

public class ConnectionGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public ConnectionGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConnectionGroupIdIsNull() {
            addCriterion("connection_group_id is null");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdIsNotNull() {
            addCriterion("connection_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdEqualTo(Integer value) {
            addCriterion("connection_group_id =", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdNotEqualTo(Integer value) {
            addCriterion("connection_group_id <>", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdGreaterThan(Integer value) {
            addCriterion("connection_group_id >", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("connection_group_id >=", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdLessThan(Integer value) {
            addCriterion("connection_group_id <", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("connection_group_id <=", value, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdIn(List<Integer> values) {
            addCriterion("connection_group_id in", values, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdNotIn(List<Integer> values) {
            addCriterion("connection_group_id not in", values, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("connection_group_id between", value1, value2, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("connection_group_id not between", value1, value2, "connectionGroupId");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameIsNull() {
            addCriterion("connection_group_name is null");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameIsNotNull() {
            addCriterion("connection_group_name is not null");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameEqualTo(String value) {
            addCriterion("connection_group_name =", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameNotEqualTo(String value) {
            addCriterion("connection_group_name <>", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameGreaterThan(String value) {
            addCriterion("connection_group_name >", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("connection_group_name >=", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameLessThan(String value) {
            addCriterion("connection_group_name <", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameLessThanOrEqualTo(String value) {
            addCriterion("connection_group_name <=", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameLike(String value) {
            addCriterion("connection_group_name like", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameNotLike(String value) {
            addCriterion("connection_group_name not like", value, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameIn(List<String> values) {
            addCriterion("connection_group_name in", values, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameNotIn(List<String> values) {
            addCriterion("connection_group_name not in", values, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameBetween(String value1, String value2) {
            addCriterion("connection_group_name between", value1, value2, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andConnectionGroupNameNotBetween(String value1, String value2) {
            addCriterion("connection_group_name not between", value1, value2, "connectionGroupName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsIsNull() {
            addCriterion("max_connections is null");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsIsNotNull() {
            addCriterion("max_connections is not null");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsEqualTo(Integer value) {
            addCriterion("max_connections =", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsNotEqualTo(Integer value) {
            addCriterion("max_connections <>", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsGreaterThan(Integer value) {
            addCriterion("max_connections >", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_connections >=", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsLessThan(Integer value) {
            addCriterion("max_connections <", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsLessThanOrEqualTo(Integer value) {
            addCriterion("max_connections <=", value, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsIn(List<Integer> values) {
            addCriterion("max_connections in", values, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsNotIn(List<Integer> values) {
            addCriterion("max_connections not in", values, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsBetween(Integer value1, Integer value2) {
            addCriterion("max_connections between", value1, value2, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsNotBetween(Integer value1, Integer value2) {
            addCriterion("max_connections not between", value1, value2, "maxConnections");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserIsNull() {
            addCriterion("max_connections_per_user is null");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserIsNotNull() {
            addCriterion("max_connections_per_user is not null");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserEqualTo(Integer value) {
            addCriterion("max_connections_per_user =", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserNotEqualTo(Integer value) {
            addCriterion("max_connections_per_user <>", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserGreaterThan(Integer value) {
            addCriterion("max_connections_per_user >", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_connections_per_user >=", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserLessThan(Integer value) {
            addCriterion("max_connections_per_user <", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserLessThanOrEqualTo(Integer value) {
            addCriterion("max_connections_per_user <=", value, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserIn(List<Integer> values) {
            addCriterion("max_connections_per_user in", values, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserNotIn(List<Integer> values) {
            addCriterion("max_connections_per_user not in", values, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserBetween(Integer value1, Integer value2) {
            addCriterion("max_connections_per_user between", value1, value2, "maxConnectionsPerUser");
            return (Criteria) this;
        }

        public Criteria andMaxConnectionsPerUserNotBetween(Integer value1, Integer value2) {
            addCriterion("max_connections_per_user not between", value1, value2, "maxConnectionsPerUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 15:15:04 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}