package com.ublwarriors.guacamole.model;

public class ConnectionParameterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer connectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String parameterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_parameter.connection_id
     *
     * @return the value of guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getConnectionId() {
        return connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_parameter.connection_id
     *
     * @param connectionId the value for guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setConnectionId(Integer connectionId) {
        this.connectionId = connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_parameter.parameter_name
     *
     * @return the value of guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_parameter.parameter_name
     *
     * @param parameterName the value for guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
}