package com.ublwarriors.guacamole.model;

public class ConnectionPermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_permission.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer connectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_permission.permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_permission.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_permission.connection_id
     *
     * @return the value of guacamole_connection_permission.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getConnectionId() {
        return connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_permission.connection_id
     *
     * @param connectionId the value for guacamole_connection_permission.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setConnectionId(Integer connectionId) {
        this.connectionId = connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_permission.permission
     *
     * @return the value of guacamole_connection_permission.permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_permission.permission
     *
     * @param permission the value for guacamole_connection_permission.permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_permission.user_id
     *
     * @return the value of guacamole_connection_permission.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_permission.user_id
     *
     * @param userId the value for guacamole_connection_permission.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}