package com.ublwarriors.guacamole.model;

public class ConnectionParameter extends ConnectionParameterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String parameterValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection_parameter.parameter_value
     *
     * @return the value of guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getParameterValue() {
        return parameterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection_parameter.parameter_value
     *
     * @param parameterValue the value for guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue;
    }
}