package com.ublwarriors.guacamole.model;

public class Connection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer connectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.connection_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String connectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.parent_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.protocol
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.max_connections
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer maxConnections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_connection.max_connections_per_user
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer maxConnectionsPerUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.connection_id
     *
     * @return the value of guacamole_connection.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getConnectionId() {
        return connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.connection_id
     *
     * @param connectionId the value for guacamole_connection.connection_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setConnectionId(Integer connectionId) {
        this.connectionId = connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.connection_name
     *
     * @return the value of guacamole_connection.connection_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getConnectionName() {
        return connectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.connection_name
     *
     * @param connectionName the value for guacamole_connection.connection_name
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setConnectionName(String connectionName) {
        this.connectionName = connectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.parent_id
     *
     * @return the value of guacamole_connection.parent_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.parent_id
     *
     * @param parentId the value for guacamole_connection.parent_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.protocol
     *
     * @return the value of guacamole_connection.protocol
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.protocol
     *
     * @param protocol the value for guacamole_connection.protocol
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.max_connections
     *
     * @return the value of guacamole_connection.max_connections
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getMaxConnections() {
        return maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.max_connections
     *
     * @param maxConnections the value for guacamole_connection.max_connections
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setMaxConnections(Integer maxConnections) {
        this.maxConnections = maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_connection.max_connections_per_user
     *
     * @return the value of guacamole_connection.max_connections_per_user
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getMaxConnectionsPerUser() {
        return maxConnectionsPerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_connection.max_connections_per_user
     *
     * @param maxConnectionsPerUser the value for guacamole_connection.max_connections_per_user
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setMaxConnectionsPerUser(Integer maxConnectionsPerUser) {
        this.maxConnectionsPerUser = maxConnectionsPerUser;
    }

	@Override
	public String toString() {
		return "Connection [connectionId=" + connectionId + ", connectionName=" + connectionName + ", parentId="
				+ parentId + ", protocol=" + protocol + ", maxConnections=" + maxConnections
				+ ", maxConnectionsPerUser=" + maxConnectionsPerUser + "]";
	}
    
}