package com.ublwarriors.guacamole.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.username
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.disabled
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.expired
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Boolean expired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.access_window_start
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Date accessWindowStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.access_window_end
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Date accessWindowEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.valid_from
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Date validFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.valid_until
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private Date validUntil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.timezone
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private String timezone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.user_id
     *
     * @return the value of guacamole_user.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.user_id
     *
     * @param userId the value for guacamole_user.user_id
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.username
     *
     * @return the value of guacamole_user.username
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.username
     *
     * @param username the value for guacamole_user.username
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.disabled
     *
     * @return the value of guacamole_user.disabled
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.disabled
     *
     * @param disabled the value for guacamole_user.disabled
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.expired
     *
     * @return the value of guacamole_user.expired
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Boolean getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.expired
     *
     * @param expired the value for guacamole_user.expired
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setExpired(Boolean expired) {
        this.expired = expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.access_window_start
     *
     * @return the value of guacamole_user.access_window_start
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Date getAccessWindowStart() {
        return accessWindowStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.access_window_start
     *
     * @param accessWindowStart the value for guacamole_user.access_window_start
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setAccessWindowStart(Date accessWindowStart) {
        this.accessWindowStart = accessWindowStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.access_window_end
     *
     * @return the value of guacamole_user.access_window_end
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Date getAccessWindowEnd() {
        return accessWindowEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.access_window_end
     *
     * @param accessWindowEnd the value for guacamole_user.access_window_end
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setAccessWindowEnd(Date accessWindowEnd) {
        this.accessWindowEnd = accessWindowEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.valid_from
     *
     * @return the value of guacamole_user.valid_from
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.valid_from
     *
     * @param validFrom the value for guacamole_user.valid_from
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.valid_until
     *
     * @return the value of guacamole_user.valid_until
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public Date getValidUntil() {
        return validUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.valid_until
     *
     * @param validUntil the value for guacamole_user.valid_until
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setValidUntil(Date validUntil) {
        this.validUntil = validUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.timezone
     *
     * @return the value of guacamole_user.timezone
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.timezone
     *
     * @param timezone the value for guacamole_user.timezone
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
}