package com.ublwarriors.guacamole.model;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.password_hash
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private byte[] passwordHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole_user.password_salt
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    private byte[] passwordSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.password_hash
     *
     * @return the value of guacamole_user.password_hash
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public byte[] getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.password_hash
     *
     * @param passwordHash the value for guacamole_user.password_hash
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setPasswordHash(byte[] passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole_user.password_salt
     *
     * @return the value of guacamole_user.password_salt
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public byte[] getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole_user.password_salt
     *
     * @param passwordSalt the value for guacamole_user.password_salt
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    public void setPasswordSalt(byte[] passwordSalt) {
        this.passwordSalt = passwordSalt;
    }
}