package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.ConnectionGroup;
import com.ublwarriors.guacamole.model.ConnectionGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
@Component
public interface ConnectionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(ConnectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(ConnectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(Integer connectionGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(ConnectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(ConnectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<ConnectionGroup> selectByExample(ConnectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    ConnectionGroup selectByPrimaryKey(Integer connectionGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ConnectionGroup record, @Param("example") ConnectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") ConnectionGroup record, @Param("example") ConnectionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKeySelective(ConnectionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKey(ConnectionGroup record);
}