package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.ConnectionPermissionExample;
import com.ublwarriors.guacamole.model.ConnectionPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectionPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(ConnectionPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(ConnectionPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(ConnectionPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(ConnectionPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(ConnectionPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<ConnectionPermissionKey> selectByExample(ConnectionPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ConnectionPermissionKey record, @Param("example") ConnectionPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") ConnectionPermissionKey record, @Param("example") ConnectionPermissionExample example);
}