package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.ConnectionHistory;
import com.ublwarriors.guacamole.model.ConnectionHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<ConnectionHistory> selectByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    ConnectionHistory selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ConnectionHistory record, @Param("example") ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") ConnectionHistory record, @Param("example") ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKeySelective(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_history
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKey(ConnectionHistory record);
}