package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.Connection;
import com.ublwarriors.guacamole.model.ConnectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(Integer connectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<Connection> selectByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    Connection selectByPrimaryKey(Integer connectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") Connection record, @Param("example") ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") Connection record, @Param("example") ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKeySelective(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByPrimaryKey(Connection record);
}