package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.ConnectionGroupPermissionExample;
import com.ublwarriors.guacamole.model.ConnectionGroupPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectionGroupPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(ConnectionGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(ConnectionGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(ConnectionGroupPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(ConnectionGroupPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(ConnectionGroupPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<ConnectionGroupPermissionKey> selectByExample(ConnectionGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ConnectionGroupPermissionKey record, @Param("example") ConnectionGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_connection_group_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") ConnectionGroupPermissionKey record, @Param("example") ConnectionGroupPermissionExample example);
}