package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.SystemPermissionExample;
import com.ublwarriors.guacamole.model.SystemPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(SystemPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(SystemPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(SystemPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<SystemPermissionKey> selectByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemPermissionKey record, @Param("example") SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_system_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") SystemPermissionKey record, @Param("example") SystemPermissionExample example);
}