package com.ublwarriors.guacamole.dao;

import com.ublwarriors.guacamole.model.UserPermissionExample;
import com.ublwarriors.guacamole.model.UserPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int countByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int deleteByPrimaryKey(UserPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insert(UserPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int insertSelective(UserPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    List<UserPermissionKey> selectByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPermissionKey record, @Param("example") UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole_user_permission
     *
     * @mbggenerated Wed Jul 13 15:15:04 CST 2016
     */
    int updateByExample(@Param("record") UserPermissionKey record, @Param("example") UserPermissionExample example);
}